
"""
Django settings for db_metadata_crawler project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/


When you start a Django project (e.g., with runserver, migrate, or shell), Django will import:
    (first loads settings.py)
    Your app's apps.py config.
    Your app’s models.py, because Django scans models during setup.
    Anything imported at the top level of those modules (including things like forms, utils, signals, etc.)
    Any module you import directly in urls.py, views.py, or elsewhere in your code.
"""

from pathlib import Path
import platform
from metadata_crawler.utilitarios import detect_runtime_environment


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

ENVIRONMENT = detect_runtime_environment()
print(f"enviroment: {ENVIRONMENT}")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sq4z=cma)0=3+rzx-en-jpn0xzp%8e%&u%$*m_@(imm)j3-*_('

# SECURITY WARNING: don't run with debug turned on in production!
# Triggering server reload to pick up templatetags
DEBUG = False

# em produção, add your production domain to CSRF_TRUSTED_ORIGINS and to ALLOWED_HOSTS:
ALLOWED_HOSTS = [
    'dimac-colop-dict-dbdesig-jobs.cloud-p.bcnet.bcb.gov.br',
    'votebem.org',
    'www.votebem.org',
    'localhost',
    '127.0.0.1',
]
CSRF_TRUSTED_ORIGINS = [
    "https://dimac-colop-dict-dbdesig-jobs.cloud-p.bcnet.bcb.gov.br",
    "https://votebem.org",
    "https://www.votebem.org",
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'metadata_crawler',
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# para onde o user vai ser redirecionado após fazer login e logout
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

ROOT_URLCONF = 'db_metadata_crawler.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'metadata_crawler.context_processors.maintenance_flag',
            ],
        },
    },
]

WSGI_APPLICATION = 'db_metadata_crawler.wsgi.application'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Set dados path based on OS
if ENVIRONMENT == 'windows' or ENVIRONMENT == 'docker-wsl':
    DADOS_PATH = BASE_DIR  # Development
else:
    DADOS_PATH = '/dados/dict-db'  # Production
DADOS_PATH = Path(DADOS_PATH)

# arquivo do sqlite incluindo o path
DB_FILE_FULLPATH = DADOS_PATH / 'dict-db.sqlite3' 
print(f"DB_FILE_FULLPATH: {DB_FILE_FULLPATH}")

# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(DB_FILE_FULLPATH),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = DADOS_PATH / 'staticfiles'

# ---------------------------------------------------------------------------
# Linhagem (dependencias de views) e modificadores DML
# ---------------------------------------------------------------------------
# Ao rastrear uma conexao MSSQL, varrer as rotinas (funcoes/SPs) de TODOS os
# bancos acessiveis do servidor, para capturar modificacoes cross-database
# (uma SP em outro banco que faz INSERT/UPDATE/DELETE em tabelas deste).
# Desligue se a varredura completa for custosa no seu ambiente.
LINEAGE_SCAN_ALL_DATABASES = True

# Artefatos JSON gerados no rastreamento e servidos pela aplicacao.
LINEAGE_JSON_PATH = BASE_DIR / 'lineage.json'
MODIFIERS_JSON_PATH = BASE_DIR / 'modifiers.json'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': str(DADOS_PATH / '___django.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        # Your app-specific loggers
        'metadata_crawler': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

