# Generated by Django 5.2.4 on 2025-08-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='database_type',
            field=models.CharField(choices=[('MSSQL', 'Microsoft SQL Server'), ('TERADATA', 'Teradata')], default='MSSQL', max_length=10),
        ),
    ]
