# Generated by Django 5.2.7 on 2025-10-23 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_crawler', '0002_databaseconnection_database_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fieldmetadata',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='databaseconnection',
            name='connection_string',
        ),
        migrations.AddField(
            model_name='metadatacomment',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='metadata_crawler.databaseconnection'),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='database_type',
            field=models.CharField(choices=[('MSSQL', 'Microsoft SQL Server'), ('TERADATA', 'Teradata')], max_length=20),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='metadatacomment',
            name='comment_type',
            field=models.CharField(choices=[('TABLE', 'Table'), ('FIELD', 'Field'), ('CONNECTION', 'Connection')], max_length=12),
        ),
        migrations.RemoveField(
            model_name='fieldmetadata',
            name='foreign_key_column',
        ),
    ]
