# Generated by Django 5.2.7 on 2025-10-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_crawler', '0003_alter_fieldmetadata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmetadata',
            name='data_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fieldmetadata',
            name='is_foreign_key',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fieldmetadata',
            name='is_nullable',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldmetadata',
            name='is_primary_key',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
