# Generated by Django 5.2.7 on 2026-10-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_crawler', '0006_switch_metadatacomment_to_name_fks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseconnection',
            name='name',
        ),
    ]
